### ISSUE TITLE
.yarn 폴더가 git 파일에 추가되는 문제가 있습니다.

### ISSUE THREAD

**Issue by devsoob** [modu-house/FE-modu-house#1]
`yarn -v`
: 3.3.0

.yarn/
.yarnrc.yml

**Comment by synuns** [comment]
제 yarn version은 `1.22.10`인데 yarn의 1버전은 .yarn 폴더를 생성하지 않습니다.
그래서 따로 gitignore 설정을 해주지 않아서 발생한 문제입니다.

제 yarn version을 최신으로 버전업시키고 yarn관련 파일들은 `.gitignore`처리해서 migration하겠습니다.

`$ yarn set version berry`

yarn의 버전업에 따른 방식 변경과 그 이유가 궁금하다면 관련 레퍼런스를 달아놓겠습니다. 확인 부탁드립니다.

- https://medium.com/wantedjobs/yarn-berry-%EC%A0%81%EC%9A%A9%EA%B8%B0-1-e4347be5987
- https://velog.io/@altmshfkgudtjr/yarn2%EC%99%80-%ED%95%A8%EA%BB%98-Plug-n-Play%EB%A5%BC-%EC%A0%81%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90
