### ISSUE TITLE
TopBar component, Login page의 UI에 약간의 수정이 필요합니다

### ISSUE THREAD

**Issue by devsoob** [modu-house/FE-modu-house#11]
- [x] width 를 줄였을 때 Login Form 도 같이 줄어들게 수정이 필요합니다.
- [ ] heigth를 줄였을 때 TopBar와 페이지 컴포넌트가 겹치는 문제를 해결해야 합니다.
- [x] TopBar 의 Logo 이미지와  h1 글자 사이의 margin이 필요합니다, 

1. width 를 줄였을 때 Login Form 도 같이 줄어들게 수정이 필요합니다.

![스크린샷 2022-12-19 오후 5 35 02](https://user-images.githubusercontent.com/107169675/208382569-31ba1cb3-950e-492e-9c10-41db4057d757.png)

2. heigth를 줄였을 때 TopBar와 페이지 컴포넌트가 겹치는 문제를 해결해야 합니다.

![스크린샷 2022-12-19 오후 5 34 12](https://user-images.githubusercontent.com/107169675/208382583-cffc5f44-7bd1-402b-bf04-7f1cf876785f.png)

3. TopBar 의 Logo 이미지와  h1 글자 사이의 margin이 필요합니다,

**Comment by synuns** [comment]
이슈 정리 너무 잘했어요👍 앞으로도 잘 남겨줘요 :)
